import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import "bootstrap-icons/font/bootstrap-icons.css";
import LoginDialog from "@/components/Login";
import SignupDialog from "@/components/Signup";
import { AppProvider } from "@/context/context";
import Sidebar from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">

      <body>

        <AppProvider>

          <Navbar />

          <LoginDialog />
          <SignupDialog />

          {children}

          <Sidebar />

        </AppProvider>

      </body>

    </html>

  );
}
